# 服务配置
Server:
  # 运行环境
  RunMode: debug
  # 服务端口
  HttpPort: 9000
  # 读取请求超时时间
  ReadTimeout: 60
  # 写入响应超时时间
  WriteTimeout: 60

# 应用配置
App:
  # 默认数据分页页数
  DefaultPageSize: 10
  # 每页最大数据条数
  MaxPageSize: 100
  # 日志文件保存路径
  LogSavePath: storage/logs
  # 日志文件名称
  LogFileName: app
  # 日志文件后缀
  LogFileExt: .log

# 数据源配置
Database:
  DBType: mysql
  Username: root
  Password: "000"
  Host: 192.168.71.5:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30